name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: golang:1.18.1-alpine
    steps:
      - name: Install pre-requisites (1)
        run: |
          apk add --no-cache make jq zip curl git npm gettext

      - name: Install pre-requisites (2)
        run: |
          go get github.com/github/hub

      - name: Checkout
        uses: actions/checkout@master

      - name: Build
        run: make binaries

      - name: Release
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          npm version patch
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
          GIT_AUTHOR_EMAIL: "actions@users.noreply.github.com"
          GIT_AUTHOR_NAME: "GitHub Actions"
